# Generated by Django 4.2 on 2023-04-12 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sex', models.BooleanField()),
                ('user_name', models.CharField(max_length=5)),
                ('user_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('user_mbti_1', models.CharField(max_length=5)),
                ('user_mbti_2', models.CharField(max_length=5)),
                ('user_mbti_3', models.CharField(max_length=5)),
                ('user_mbti_4', models.CharField(max_length=5)),
                ('user_school', models.CharField(max_length=20)),
                ('user_image', models.ImageField(upload_to='immigration/images/%Y/%m/%d/')),
                ('user_kakaoid', models.CharField(max_length=40)),
                ('want_age_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('want_age_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('want_mbti_1', models.CharField(max_length=5)),
                ('want_mbti_2', models.CharField(max_length=5)),
                ('want_mbti_3', models.CharField(max_length=5)),
                ('want_mbti_4', models.CharField(max_length=5)),
                ('user_survey_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
