# Generated by Django 4.2 on 2023-04-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='Q_pid_list',
            field=models.TextField(null=True),
        ),
    ]
