# Generated by Django 4.2 on 2023-04-27 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('immigration', '0002_usersurvey_q_pid_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersurvey',
            name='want_mbti_1',
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='want_mbti_2',
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='want_mbti_3',
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='want_mbti_4',
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='user_model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='want_mbti',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='Q_pid_list',
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='user_image',
            field=models.ImageField(null=True, upload_to='immigration/images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='Q_pid_list',
            field=models.ManyToManyField(blank=True, related_name='user_q_pid_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
