# Generated by Django 4.2 on 2023-04-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0003_remove_usersurvey_want_mbti_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='user_password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
