# Generated by Django 4.2 on 2023-05-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0007_alter_matching_final_matching_alter_matching_ok_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='final_matching',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matching',
            name='ok_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
