# Generated by Django 4.2 on 2023-05-13 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_matching_no_list_profile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_image',
        ),
    ]
